name: Publish to NUGET
on:
  push:
    tags: "*"
jobs:
  publish:
    name: List on NuGet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release "Lykke.Common.ApiLibrary.sln"
    - name: Create the package
      run: dotnet pack --include-symbols --include-source --configuration Release src/Lykke.Common.ApiLibrary /p:Version=${GITHUB_REF#refs/tags/}
    - name: Publish the package to Nuget
      run: dotnet nuget push src/Lykke.Common.ApiLibrary/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }} --skip-duplicate
